//LOCALHOST

###Get all users
GET http://localhost:3000/users

###Get all products
GET http://localhost:3000/products


###Get user by Id
GET http://localhost:3000/users/68e0c7056299d74ed0590744

###Get products by Id
GET http://localhost:3000/products/68e69db9fddc0bf68098b0e5

###Create users
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Akin",
    "lastName": "Femi",
    "email": "ogoade@examble.com",
    "favoriteColor": "red",
    "birthday": "11/27/1993"
}

###Create products
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name": "Senator Wear",
    "price": "N150,000",
    "category": "Clothing",
    "brand": "Sapphy Array",
    "inStock": "true",
    "sizes": "Small  Medium  Large  Extra-Large"
}


###Put users
PUT http://localhost:3000/users/68e0c68b6299d74ed0590743 HTTP/1.1
content-type: application/json

{
    "firstName": "Akin",
    "lastName": "Femi",
    "email": "akinfemi@gmail.com",
    "favoriteColor": "Blue",
    "birthday": "11/27/1990"
}

###Put products
PUT http://localhost:3000/products/68e75e1e586a7f94e928c6ec HTTP/1.1
content-type: application/json

{
    "name": "Sneakers",
    "price": "80,000",
    "category": "Shoe",
    "brand": "Nike",
    "inStock": "true",
    "sizes": "42, 44, 45"
}

###Delete users
DELETE http://localhost:3000/users/68dfddbf299f20e7cddfe050 HTTP/1.1

###Delete products
DELETE http://localhost:3000/products/68e6a2ce4d968d4fe88708e7 HTTP/1.1